DROP TABLE PHONE;


CREATE TABLE PHONE(
        USERNONO NUMBER PRIMARY KEY,
        USERNAME VARCHAR2(20) NOT NULL,
        AGE NUMBER NOT NULL,
        ADDRESS VARCHAR2(50) NOT NULL,
        PHONENUM VARCHAR2(14) NOT NULL
);

SELECT * FROM PHONE;

CREATE SEQUENCE SEQ_USERNONO
NOCACHE;

INSERT INTO PHONE
VALUES(SEQ_USERNONO.NEXTVAL, '½ÅÂ¯±¸', 10, '¶±ÀÙ¸¶À»', '01011112222');

INSERT INTO PHONE
VALUES(SEQ_USERNONO.NEXTVAL, '½ÅÂ¯¾Æ', 6, 'Â¯±¸³×Áý', '01033334444');


COMMIT;



